---

- name: Deploy lamp stack application
  hosts: all
  become: yes
  roles:
    - common

    # Install and Configure Database
- name: Deploy lamp stack application
  hosts: lamp-db
  become: yes
  roles:
    - mysql

- name: Deploy lamp stack application
  hosts: lampweb
  become: yes
  roles:
    - httpd-php


# ---

# - name: Deploy lamp stack application
#   hosts: all
#   become: yes
#   tasks:
#     - include_tasks: tasks/common.yml

#     # Install and Configure Database
# - name: Deploy lamp stack application
#   hosts: lamp-db
#   gather_facts: yes
#   become: yes
#   tasks:
#     - include_tasks: tasks/db.yml

# - name: Deploy lamp stack application
#   hosts: lampweb
#   gather_facts: yes
#   become: yes
#   tasks:
#     - include_tasks: tasks/web.yml